main_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('', RedirectView.as_view(url='order/', permanent=False)),
    path('admin/', admin.site.urls),
    path('order/', include('order.urls')),
]

urlpatterns += staticfiles_urlpatterns()

order/urls.py
from django.urls import path, re_path
from . import views

app_name = 'order'


urlpatterns = [
    path('', views.index, name='index'),
    path('add', views.add_order, name='add-order'),
    re_path(r'v/(?P<hid>.+)$', views.read_order_hid, name='read-order-hid'),
    path('browse', views.browse_order, name='browse'),
    path('filter', views.filter_order, name='filter'),
    re_path(r'send/(?P<order_id>.+)$', views.send_order, name='send-order'),
]

order/models.py
# -*- coding: utf-8 -*-
from enum import Enum

import base62
from django.conf import settings
from django.core.mail import send_mail
from django.db import models

from .tools import sendsms


class Product(models.Model):
    name = models.CharField(max_length=30)
    price = models.IntegerField(default=0)
    call_name = models.CharField(max_length=30, default="")
    enabled = models.BooleanField(default=True, blank=True)

    class Meta:
        verbose_name = u'상품'
        verbose_name_plural = u'상품'

    def __str__(self):
        return "%s / %d원" % (self.name, self.price)


class OrderManager(models.Manager):
    def get_with_hid(self, hid):
        h = base62.decode(hid)
        i = h ^ settings.HKEY
        i = i >> settings.HP
        return self.get(id=i)


class Order(models.Model):
    product = models.ForeignKey(Product, models.SET_NULL, verbose_name=u"상품", null=True, blank=True)
    qty = models.IntegerField(default=0)
    buyer = models.CharField("주문자 이름", max_length=30, default="", null=False, blank=False)
    buyer_contact = models.CharField("주문자 연락처", max_length=255, default="", null=True, blank=False)
    buyer_contact_type = models.PositiveSmallIntegerField(default=0, blank=True)
    sender = models.CharField("입금자 이름", max_length=30, default="", null=True, blank=False)
    recipient = models.CharField("받는 사람", max_length=30, default="", null=True, blank=False)
    recipient_phone_number = models.CharField("받는사람 전화번호", max_length=20, default="", null=True, blank=False)
    recipient_zipcode = models.CharField("우편번호", max_length=5, default="", null=True, blank=False)
    recipient_base_address = models.CharField("주소", max_length=300, default="", null=True, blank=False)
    recipient_additional_address = models.CharField("상세주소", max_length=300, default="", null=True, blank=True)
    memo = models.TextField("특이사항", default="", null=True, blank=True)
    shipping_memo = models.CharField(max_length=300, default="", null=True, blank=True)
    shipping_option = models.PositiveSmallIntegerField(default=0, blank=True)

    status_payment = models.BooleanField(default=False, blank=True)
    status_payment_sms = models.BooleanField(default=False, blank=True)
    status_shipping = models.BooleanField(default=False, blank=True)

    shipping_order = models.PositiveSmallIntegerField(default=0, blank=True)
    shipping_id = models.PositiveSmallIntegerField(default=0, blank=True)

    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    @property
    def pn(self):
        value = self.recipient_phone_number
        if value is None:
            return ""
        phone = '%s-%s-%s' % (value[0:3], value[3:7], value[7:11])
        return phone

    @property
    def hid(self):
        k = self.id << settings.HP
        return base62.encode(k ^ settings.HKEY)

    def sum(self):
        return self.qty * self.product.price

    class NotificationType(Enum):
        CONFIRMED, COMPLETED, SHIPPED = range(3)

    def notify(self, type):
        if type == self.NotificationType.CONFIRMED:
            title = '주문확인되었습니다'
            message = '주문확인되었습니다. 상세주문내역확인 https://neungju.com/order/v/%s' % (self.hid,)  # Message
        elif type == self.NotificationType.COMPLETED:
            title = '입금이 확인되었습니다'
            message = '입금이 확인되었습니다. 상세주문내역확인 https://neungju.com/order/v/%s' % (self.hid,)  # Message
        elif type == self.NotificationType.SHIPPED:
            title = '배송이 시작되었습니다'
            message = '배송이 시작되었습니다. 상세주문내역확인 https://neungju.com/order/v/%s' % (self.hid,)  # Message
        if self.buyer_contact_type == 0:
            sendsms(self.buyer_contact, message)
        else:
            send_mail(
                u'[복숭아] %s' % (title,),
                message,
                settings.NOTIFICATION_EMAIL_SENDER,
                [self.buyer_contact],
                fail_silently=False,
            )

    def __str__(self):
        try:
            name = "%d - %s/%s/%d" % (self.id, self.buyer, self.product.name, self.qty)
        except TypeError:
            name = "<<ERROR>>"
        return name

    objects = OrderManager()

order/forms.py
from django.forms import ModelForm
from django.core.validators import validate_email
from django.core.exceptions import ValidationError
from django import forms
from .models import Order, Product
import re


class OrderForm(ModelForm):

    product = forms.ModelChoiceField(label=u"상품", queryset=Product.objects.filter(enabled=True))
    memo = forms.CharField(label=u"특이사항/메모 - 추천인, 토요일 택배 수령, 등등", required=False, widget=forms.Textarea(attrs={'rows': 4, 'cols': 40}))

    def clean(self):
        cleaned_data = super().clean()
        t = cleaned_data['buyer_contact_type']
        if 'buyer_contact' in self.cleaned_data:
            if t == 0:
                cleaned_data['buyer_contact'] = self.clean_phone_number(cleaned_data['buyer_contact'])
                if not cleaned_data['buyer_contact']:
                    msg = '전화번호 형식에 문제가 있습니다.'
                    self.add_error('buyer_contact', msg)
            else:
                validate_email(cleaned_data['buyer_contact'])
        else:
            msg = '연락처가 비어 있습니다.'
            self.add_error('buyer_contact', msg)
        return cleaned_data

    def clean_recipient_phone_number(self):
        data = self.cleaned_data['recipient_phone_number']
        if data is None:
            try:
                data = self.cleaned_data['buyer_contact']
            except KeyError:
                raise ValidationError('받는 사람 연락처가 비어 있습니다.')
        data = self.clean_phone_number(data)
        if data is None:
            raise ValidationError('잘못된 연락처 입니다.')
        return data

    @staticmethod
    def clean_phone_number(s):
        if s is not None:
            return re.sub(r'[^\d]', '', s)
        else:
            return ''

    class Meta:
        model = Order
        fields = ['product', 'qty', 'buyer', 'buyer_contact', 'buyer_contact_type', 'sender', 'recipient', 'recipient_phone_number', 'recipient_zipcode', 'recipient_base_address', 'recipient_additional_address', 'memo', 'shipping_option']

order/views.py
import uuid

from django.core.paginator import Paginator, PageNotAnInteger
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from .forms import OrderForm
from .models import Order, Product
from django.conf import settings


def index(request):
    return render(request, 'order/index.html')


def add_order(request):
    if settings.ORDER_CLOSE:
        return render(request, 'order/closed.html')
    if request.method == 'POST':
        form = OrderForm(request.POST)
        if form.is_valid():
            order = form.save()
            return redirect('order:read-order-hid', hid=str(order.hid))
    else:
        form = OrderForm(initial={'product': Product.objects.first()})

    return render(request, 'order/add.html', {"form": form})


def read_order_hid(request, hid):
    try:
        order = Order.objects.get_with_hid(hid=hid)
        return render(request, 'order/read.html', {"order": order})
    except Order.DoesNotExist:
        return redirect('order:index')


@login_required
def browse_order(request):
    objects = Order.objects.order_by("shipping_id", "id").filter(shipping_id__gt=0).filter(shipping_id__lt=900)
    start = request.GET.get('start', None)
    if start:
        end = request.GET.get('end', None)
        start = int(start) - 1
        end = int(end)
        orders = objects[start:end]
    else:
        try:
            page = request.GET.get('page', 1)
        except PageNotAnInteger:
            page = 1
        p = Paginator(objects, 10)
        orders = p.get_page(page)

    return render(request, 'order/browse.html', {"items": orders})


@login_required
def filter_order(request):
    orders = Order.objects.filter(shipping_id=0).order_by("id")
    return render(request, 'order/filter.html', {"items": orders})


@login_required
def send_order(_, order_id):
    order = Order.objects.get(id=order_id)
    a = Order.objects.filter(shipping_id__lt=900).order_by("-shipping_id").first()
    order.shipping_id = a.shipping_id + 1
    order.save()
    return redirect('order:filter')

order/templates/order/add.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% block content %}
<div class="row">
  <div class="col-lg-12">
    <div><h2>판매중</h2></div>
    {% include 'order/notice.html' %}
    <form method="post" class="form-horizontal">
      {% csrf_token %}
      <input type="hidden" name="sid" value="{{ form.sid.value }}">
      {% bootstrap_form_errors form type='non_fields' %}

      {% bootstrap_field form.product layout='horizontal' %}

      <div class="row pb-3 mb-3 border-bottom">
        {% bootstrap_label "수량" label_for="qty" label_class="col-md-2"%}
        <div class="col-md-3">
          <select class="form-control{% if form.buyer_contact.errors %} is-invalid{% elif form.is_bound %} is-valid {% endif %}" name="qty">
            {% for i in "xxxx" %}
            <option value="{{ forloop.counter }}" {% if form.qty == forloop.counter %}
                    selected{% endif %}>{{ forloop.counter }}
            </option>
            {% endfor %}
          </select>
        </div>
      </div>

      {% bootstrap_field form.buyer layout='horizontal' %}

      <div class="row mb-3 row">
        <label class="col-md-2 control-label col-form-label" for="id_buyer_contact" id="buyer_contact_label">주문자 전화번호</label>
        <div class="col-md-3  has-validation">
          <input id="buyer_contact_type" name="buyer_contact_type" type="hidden" value="{{ form.buyer_contact_type.value |default_if_none:'0' }}">
          <input type="text" id="buyer_contact" name="buyer_contact" class="form-control{% if form.buyer_contact.errors %} is-invalid{% elif form.is_bound %} is-valid {% endif %}" placeholder="ex) 01012341234" title="" required="" value="{{ form.buyer_contact.value |default_if_none:'' }}" aria-describedby="inputGroupPrepend3 validationServerUsernameFeedback" >
          {% if form.buyer_contact.errors %}
            {% for text in form.buyer_contact.errors %}
              <div id="validationServerUsernameFeedback" class="invalid-feedback">{{ text|escape }}</div>
            {% endfor %}
          {% endif %}
        </div>
        <div class="col-md-6 pt-1">
          <a href="#" class="btn btn-warning btn-sm" id="altermode">전화번호 대신 Email 입력</a> <small>(해외 거주시 클릭)</small>
        </div>
      </div>

      <hr/>

      {% bootstrap_field form.sender layout="horizontal" horizontal_field_class="col-md-4" addon_after_class=None addon_after='<a class="btn btn-sm enabler">이름 수정</a>' %}
      <hr/>
      {% bootstrap_field form.recipient layout="horizontal" horizontal_field_class="col-md-4" addon_after_class=None addon_after='<a class="btn btn-sm enabler">이름 수정</a>' %}
      {% bootstrap_field form.recipient_phone_number layout="horizontal" horizontal_field_class="col-md-4" addon_after_class=None addon_after='<a class="btn btn-sm enabler">수정</a>' %}

      <div class="row mb-3">
        <div class="offset-md-2 col-md-10">
        <input class="btn btn-primary" type="button" id="set_address"
           value="우편번호/주소 입력"/>
        </div>
      </div>
      <div class="row mb-3">
        <div id="wrap"
         style="display:none;border:1px solid;width:500px;height:300px;margin:5px 0;position:relative">
        <img src="//t1.daumcdn.net/localimg/localimages/07/postcode/320/close.png"
           id="btnFoldWrap"
           style="cursor:pointer;position:absolute;right:0px;top:-1px;z-index:1"
           onclick="foldDaumPostcode()" alt="접기 버튼" />
        </div>
      </div>

      {% bootstrap_field form.recipient_zipcode layout='horizontal' horizontal_field_class="col-md-2"%}
      {% bootstrap_field form.recipient_base_address layout='horizontal' horizontal_field_class="col-md-7"%}
      {% bootstrap_field form.recipient_additional_address layout='horizontal' horizontal_field_class="col-md-7"%}
      <hr/>
      {% bootstrap_field form.memo layout='horizontal' horizontal_field_class="col-md-7" %}
      <hr/>
      <div class="row mb-3">
        <div class="col-md-4 offset-md-2">
          <button class="btn btn-primary btn-lg" type="submit">주문하기</button>
        </div>
      </div>
    </div>
  </form>
</div>
{% endblock %}
{% block script %}
<!-- Modal -->
<div class="modal" tabindex="-1" id = "myModal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="myModalLabel">우편번호 찾기</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body" id="postcodebox">
      </div>
      <div class="modal-footer">
      </div>
    </div>
  </div>
</div>


<script src="https://ssl.daumcdn.net/dmaps/map_js_init/postcode.v2.js"></script>

<script>

  var element_wrap = document.getElementById('postcodebox');
    function foldDaumPostcode() {
        // iframe을 넣은 element를 안보이게 한다.
        element_wrap.style.display = 'none';
    }
  $(document).ready(function(){
    $(".enabler").each(function(i, e){
      var v = $(this).parent().parent().children().first();
      if(v.val() === "") {
        v.prop('readonly', true);
        $(this).on("click", function(e) {
          $(this).parent().parent().children().first().prop('readonly', false);
        });
      }
    });
    $("input[name=recipient_zipcode]").prop('readonly', true);
    $("input[name=recipient_base_address]").prop('readonly', true);
    $("input[name=buyer]").on('change', function(e){
      if($("#id_sender").prop('readonly')) {
        $("#id_sender").val($(this).val());
      }
      if($("#id_recipient").prop('readonly')) {
        $("#id_recipient").val($(this).val());
      }
    });
    $("input[name=buyer_contact]").on('change', function(e){
      if($("#id_recipient_phone_number").prop('readonly')) {
        $("#id_recipient_phone_number").val($(this).val());
      }
    });
    $("input[name=buyer]").on('change', function(e){
      if($("#id_sender").prop('readonly')) {
        $("#id_sender").val($(this).val());
      }
      if($("#id_recipient").prop('readonly')) {
        $("#id_recipient").val($(this).val());
      }
    });
    $("#altermode").on("click", function() {
      $("#buyer_contact").attr("placeholder", "noname@gmail.com");
      $("#buyer_contact_type").val(1);
      $("#buyer_contact_label").text("주문자 이메일");

      $("#id_recipient_phone_number").prop("readonly", false);
      $("#id_recipient").prop("readonly", false);
      $("#id_recipient_phone_number").val("");
      $("#id_recipient").val("");
    });

    $("#set_address").on("click", function() {
      new daum.Postcode({
        shorthand: true,
        oncomplete: function(data) {
          var fullRoadAddr = data.roadAddress; // 도로명 주소 변수

          $("input[name=recipient_zipcode]").val(data.zonecode);
          $("input[name=recipient_base_address]").val(fullRoadAddr);

          $("#zip_code").val(data.zonecode);
          $("#road_address").val(fullRoadAddr);

          if(data.buildingName !== ''){
            $("input[name=recipient_additional_address").val(data.buildingName + " ");
          }
          $('#myModal').modal('hide');
        },
        width : '100%',
        maxSuggestItems : 5
      }).embed(element_wrap);
      $('#myModal').modal('show');
    });
  });
</script>
{% endblock %}

order/templates/order/bank.html
<div class="row">
  <div class="col-sm-3"><h4>입금할 곳</h4></div>
  <div class="col-sm-9">
    <span class="d-md-none"><a class="btn btn-primary" href="https://qr.kakaopay.com/EDITHERE">⚡ 카카오 페이로 바로 송금 ⚡</a></span>
    <h5>은행계좌</h5>
  </div>
</div>

<div class="row">
  <div class="offset-sm-3 col-sm-9">
    <div class="mb-2">
      도도뱅크 : 123-123213-12312 김도도 <button class="btn btn-success btn-sm cpbutton" type="button" data-toggle="tooltip" data-placement="button" title="클립보드로 복사" data-v="도도 123-1231233-123 김도도">클립보드로 복사</button>
    </div>
    <div>
        <ul>
          <li>입금자명을 꼭 확인해주세요.</li>
      </ul>
    </div>
  </div>
</div>

order/templates/order/browse.html
{% extends "base_print.html" %}
{% block content %}
<div class="container">
  <table class="table table-bordered">
    <thead>
      <tr>
        <th class="col-md-">연번</th>
        <th class="col-md-">종류</th>
        <th class="col-md-">수량</th>
        <th class="col-md-">받는사람</th>
        <th class="col-md-2">전화번호</th>
        <th class="col-md-5">주소</th>
        <th class="col-md-2">메모</th>
      </tr>
    </thead>
    <tbody>
      {% for item in items %}
        <tr>
          <td>{{ item.shipping_id }}</td>
          <td>{{ item.product.call_name }}</td>
          <td>{{ item.qty }}</td>
          <td>{{ item.recipient }}</td>
          <td>{{ item.pn }}</td>
          <td>({{ item.recipient_zipcode }})<br/>
          {{ item.recipient_base_address }}<br/>{{ item.recipient_additional_address|default_if_none:'' }}</td>
          <td>
            {{ item.shipping_memo|default_if_none:'' }}{% if item.buyer != item.recipient %}(보낸사람:{{ item.buyer }}){% endif %}
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}

order/templates/order/closed.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<main>
  <p>판매가 마감되었습니다.</p>
</main>
{% endblock %}

order/templates/order/filter.html
{% extends "base_print.html" %}
{% block content %}
<div class="container">
  <table class="table table-bordered">
    <thead>
      <tr>
        <th>연번</th>
        <th>종류</th>
        <th>수량</th>
        <th>받는사람</th>
        <th>전화번호</th>
        <th>주소</th>
        <th>배송메모</th>
        <th>결제</th>
        <th>Action</th>
        <th>메모</th>
      </tr>
    </thead>
    <tbody>
      {% for item in items %}
        <tr>
          <td>{{ item.id }}</td>
          <td>{{ item.product.call_name }}</td>
          <td>{{ item.qty }}</td>
          <td>{{ item.buyer }} / {{ item.recipient }}</td>
          <td>{{ item.pn }}</td>
          <td>
            ({{ item.recipient_zipcode }})<br/>{{ item.recipient_base_address }}<br/>{{ item.recipient_additional_address }}
          </td>
          <td>{{ item.shipping_memo|default_if_none:'' }}</td>
          <td>{% if item.status_payment %}T{% else %}NOOOOO{% endif %}
          <td><a href="{% url 'order:send-order' item.id %}">send</a></td>
          <td>{{ item.memo|default_if_none:'' }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}

order/templates/order/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<main>
  <h1>복숭아</h1>
  <p class="fs-5 col-md-8">수박이 왔어요 수박 달고 맛있는 복숭아</p>
  <div class="mb-5">
    <a href="{% url 'order:add-order' %}" class="btn btn-primary btn-lg px-4"><span class="network-name">주문하기</span></a>
  </div>
</main>
{% endblock %}

order/templates/order/read.html
{% extends "base.html" %}
{% load humanize %}
{% block content %}
<div class="container">
    <h1 class="text-center">🎉 주문 완료 🎉</h1>
    <h4>다음과 같이 주문이 전달되었습니다.</h4>
    <div class="row">
        <div class="col-sm-3"><h4>주문자 / 입금자</h4></div>
        <div class="col-sm-9"> {{ order.buyer|default_if_none:""}} ({{ order.buyer_contact }}) ({{ order.sender|default_if_none:""}})</div>
    </div>
    <div class="row">
        <div class="col-sm-3"><h4>상품정보</h4></div>
        <div class="col-sm-9"> {{ order.product.name }}({{ order.product.price|intcomma }}) x {{ order.qty }} box</div>
    </div>
    <div class="row">
        <div class="col-sm-3"><h4>배송 정보 : </h4></div>
    </div>
    <div class="row">
        <div class="offset-sm-3 col-sm-9"> 받는 사람 : {{ order.recipient|default_if_none:"" }}({{ order.recipient_phone_number|default_if_none:""  }})</div>
    </div>
    <div class="row">
        <div class="offset-sm-3 col-sm-9"> {{ order.recipient_base_address|default_if_none:"" }} {{ order.recipient_additional_address|default_if_none:"" }}
        </div>
    </div>
    <div class="row">
        <div class="col-sm-3"><h4>특이사항/메모</h4></div>
        <div class="col-sm-9"> {{ order.memo|default_if_none:"" }}</div>
    </div>
    <hr/>
    <div class="row">
        <div class="col-sm-3"><h4>총액</h4></div>
        <div class="col-sm-9"> {{ order.sum|intcomma }}</div>
    </div>
    {% if order.status_shipping %}
    <div class="row">
        <div class="col-sm-3"><h4>주문 상태</h4></div>
        <div class="col-sm-9"><h4>배송중</h4></div>
    </div>
    {% elif order.status_payment %}
    <div class="row">
        <div class="col-sm-3"><h4>입금할 곳</h4></div>
        <div class="col-sm-9"><h4>입금확인완료</h4></div>
    </div>
    {% else %}
    {% include 'order/bank.html' %}
    {% endif %}
    <div class="row">
      <div class="col-sm-12">
        <a class="btn btn-success" href="{% url 'order:index' %}"> 홈으로</a>
        <a class="btn btn-primary" href="{% url 'order:add-order' %}">새 주문</a>
      </div>
    </div>
</div>
{% endblock %}
{% block script %}
<script>
$(document).ready(function() {
  $('.cpbutton').tooltip();
  $('.cpbutton').click(function(){
    var $temp = $("<input>");
    $("body").append($temp);
    var v = $(this).attr("data-v");
    $temp.val(v).select();
    document.execCommand("copy");
    $temp.remove();
    var title = "복사됨";
    $(this).attr('title', title).attr('data-bs-original-title', title).tooltip('update').tooltip('show');
    title = "클립보드로 복사";
    $(this).attr('title', title).attr('data-bs-original-title', title).tooltip('update');
  });
});
</script>
{% endblock %}